# Generated by Django 5.0.3 on 2024-04-16 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_formdata_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='formdata',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_emale', message='Введіть валідну пошту.')], verbose_name='Пошта'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.productdescription'),
        ),
    ]
